[project]
name = "py4amitex"
version = "1.0.0"
description="Parametrize and run AMITEX simulations"
readme = "README.md"
authors = [
  { name = "Aldo Marano", email = "aldo.marano@onera.fr" },
  { name = "G. Bareigts", email = "guillame.bareigts@cea.com" },
]


[build-system]
requires = ["scikit-build-core>=0.3.3"]
build-backend = "scikit_build_core.build"

requires-python = ">=3.8"

dependencies = [
    "numpy",
    "vtk"
]

[project.optional-dependencies]
test = ["pytest"]
lint = [
  "black",
  "flake8"
]

[tool.scikit-build]
wheel.expand-macos-universal-tags = true
# wheel.packages = ["bindings/python/src/amitex"]
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
AMITEX_TESTS = "OFF"
AMITEX_EXAMPLES = "OFF"
AMITEX_PYTHON = "ON"

[tool.pytest.ini_options]
addopts = [
    "--junitxml=build/test-results-python.xml",
]
testpaths = ["cpp4amitex/bindings/python", "py4amitex/microgen"]

#[tool.cibuildwheel]
#test-command = "pytest {project}/tests"
#test-extras = ["test"]
#test-skip = ["*universal2:arm64"]
#build-verbosity = 1
